# Generated by Django 5.1.6 on 2025-12-13 11:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_links',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('brand_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=255, unique=True)),
                ('brand_photo', models.ImageField(blank=True, null=True, upload_to='brands/')),
            ],
            options={
                'db_table': 'car_brands',
            },
        ),
        migrations.CreateModel(
            name='CoverPhoto',
            fields=[
                ('photo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cover_photos',
            },
        ),
        migrations.CreateModel(
            name='SalesRepresentative',
            fields=[
                ('representative_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('judet', models.CharField(choices=[('Alba', 'Alba'), ('Arad', 'Arad'), ('Argeș', 'Argeș'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Brăila', 'Brăila'), ('Buzău', 'Buzău'), ('Caraș-Severin', 'Caraș-Severin'), ('Călărași', 'Călărași'), ('Cluj', 'Cluj'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Gorj', 'Gorj'), ('Harghita', 'Harghita'), ('Hunedoara', 'Hunedoara'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Ilfov', 'Ilfov'), ('Maramureș', 'Maramureș'), ('Mehedinți', 'Mehedinți'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Satu Mare', 'Satu Mare'), ('Sălaj', 'Sălaj'), ('Sibiu', 'Sibiu'), ('Suceava', 'Suceava'), ('Teleorman', 'Teleorman'), ('Timiș', 'Timiș'), ('Tulcea', 'Tulcea'), ('Vaslui', 'Vaslui'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Municipiul București', 'Municipiul București')], max_length=50)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone must be exactly 10 digits.')])),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sales_representatives',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('current_km', models.PositiveIntegerField(verbose_name='Current Mileage (KM)')),
                ('last_km_updated_at', models.DateTimeField(verbose_name='Last Mileage Update')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars_of_this_brand', to='myapp.carbrand')),
            ],
            options={
                'db_table': 'cars',
            },
        ),
        migrations.CreateModel(
            name='CarObligation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('obligation_type', models.CharField(choices=[('ITP', 'ITP (Inspecția Tehnică Periodică)'), ('RCA', 'RCA (Asigurare Obligatorie Răspundere Civilă Auto)'), ('CASCO', 'CASCO (Asigurare Facultativă Auto)'), ('ROVINIETA', 'Rovinietă (Taxă de Drum/Vignetă)'), ('AUTO_TAX', 'Impozit Auto Anual'), ('OIL_CHANGE', 'Schimb Ulei'), ('AIR_FILTER', 'Filtru de Aer'), ('CABIN_FILTER', 'Filtru de Polen/Habitaclu'), ('BRAKE_CHECK', 'Verificare Frâne'), ('COOLANT', 'Verificare/Schimb Lichid de Răcire'), ('BATTERY', 'Verificare/Înlocuire Baterie'), ('TIRES', 'Anvelope (Schimb Sezonier)'), ('WIPERS', 'Ștergătoare de Parbriz'), ('FIRE_EXTINGUISHER', 'Extinctor'), ('FIRST_AID_KIT', 'Trusă de Prim Ajutor')], max_length=50, verbose_name='Obligation Type')),
                ('reminder_type', models.CharField(choices=[('LEGAL', 'Legal/Administrativ'), ('MECHANICAL', 'Mecanică/Întreținere'), ('SAFETY', 'Siguranță/Echipament'), ('FINANCIAL', 'Financiar/Asigurări'), ('SEASONAL', 'Sezonier/Operațional'), ('OTHER', 'Altele')], max_length=20, verbose_name='Reminder Type')),
                ('doc_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Document URL')),
                ('due_date', models.DateField(verbose_name='Obligation Due Date')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='myapp.car', verbose_name='Car')),
            ],
            options={
                'db_table': 'car_obligations',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('service_photo', models.ImageField(upload_to='services/')),
                ('category', models.CharField(choices=[('mecanic_auto', 'Mecanic Auto'), ('autocolant_folie_auto', 'Autocolant & Folie Auto'), ('detailing_auto_profesionist', 'Detailing Auto Profesionist'), ('itp', 'ITP'), ('tapiterie_auto', 'Tapițerie Auto'), ('vulcanizare_auto_mobila', 'Vulcanizare Auto Mobilă'), ('tractari_auto', 'Tractări Auto'), ('tuning_auto', 'Tuning Auto'), ('spalatorie_auto', 'Spălătorie Auto'), ('climatizare_auto', 'Climatizare Auto'), ('caroserie_si_vopsitorie', 'Caroserie și Vopsitorie'), ('electrica_auto', 'Electrica Auto')], max_length=50)),
                ('tags', models.ManyToManyField(blank=True, related_name='services', to='myapp.tag')),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('profile_photo', models.URLField()),
                ('user_type', models.CharField(choices=[('client', 'Client'), ('supplier', 'Supplier')], max_length=20)),
                ('business_address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, choices=[('Bucharest', 'Bucharest'), ('Cluj-Napoca', 'Cluj-Napoca'), ('Timișoara', 'Timișoara'), ('Iași', 'Iași'), ('Constanța', 'Constanța'), ('Craiova', 'Craiova'), ('Brașov', 'Brașov'), ('Galați', 'Galați'), ('Ploiești', 'Ploiești'), ('Oradea', 'Oradea')], max_length=50, null=True)),
                ('sector', models.CharField(blank=True, choices=[('sector_1', 'Sector 1'), ('sector_2', 'Sector 2'), ('sector_3', 'Sector 3'), ('sector_4', 'Sector 4'), ('sector_5', 'Sector 5'), ('sector_6', 'Sector 6'), ('no_sector', 'No Sector')], max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cover_photos', models.ManyToManyField(blank=True, related_name='users', to='myapp.coverphoto')),
                ('django_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='myapp.userprofile')),
            ],
            options={
                'db_table': 'user_devices',
            },
        ),
        migrations.CreateModel(
            name='SupplierBrandService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(choices=[('Bucharest', 'Bucharest'), ('Cluj-Napoca', 'Cluj-Napoca'), ('Timișoara', 'Timișoara'), ('Iași', 'Iași'), ('Constanța', 'Constanța'), ('Craiova', 'Craiova'), ('Brașov', 'Brașov'), ('Galați', 'Galați'), ('Ploiești', 'Ploiești'), ('Oradea', 'Oradea')], max_length=50)),
                ('sector', models.CharField(blank=True, choices=[('sector_1', 'Sector 1'), ('sector_2', 'Sector 2'), ('sector_3', 'Sector 3'), ('sector_4', 'Sector 4'), ('sector_5', 'Sector 5'), ('sector_6', 'Sector 6'), ('no_sector', 'No Sector')], max_length=20, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_services', to='myapp.carbrand')),
                ('services', models.ManyToManyField(related_name='supplier_brand_services', to='myapp.service')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_services', to='myapp.userprofile')),
            ],
            options={
                'db_table': 'supplier_brand_services',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reviews', to='myapp.userprofile')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_reviews', to='myapp.userprofile')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('completed', 'Completed')], max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_requests', to='myapp.userprofile')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_requests', to='myapp.userprofile')),
            ],
            options={
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to='myapp.userprofile')),
            ],
            options={
                'db_table': 'password_reset_tokens',
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to='myapp.userprofile')),
            ],
            options={
                'db_table': 'otp_verifications',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('new_message', 'New Message'), ('supplier_approval', 'Supplier Approval'), ('request_update', 'Request Update'), ('general_notification', 'General Notification')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='myapp.userprofile')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='myapp.userprofile', verbose_name='Owner'),
        ),
        migrations.CreateModel(
            name='SupplierReferral',
            fields=[
                ('referral_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('has_received_commission', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='myapp.salesrepresentative')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='myapp.userprofile')),
            ],
            options={
                'db_table': 'supplier_referrals',
                'unique_together': {('sales_representative', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_open', models.TimeField(default='08:00')),
                ('monday_close', models.TimeField(default='19:00')),
                ('monday_closed', models.BooleanField(default=False)),
                ('tuesday_open', models.TimeField(default='08:00')),
                ('tuesday_close', models.TimeField(default='19:00')),
                ('tuesday_closed', models.BooleanField(default=False)),
                ('wednesday_open', models.TimeField(default='08:00')),
                ('wednesday_close', models.TimeField(default='19:00')),
                ('wednesday_closed', models.BooleanField(default=False)),
                ('thursday_open', models.TimeField(default='08:00')),
                ('thursday_close', models.TimeField(default='19:00')),
                ('thursday_closed', models.BooleanField(default=False)),
                ('friday_open', models.TimeField(default='08:00')),
                ('friday_close', models.TimeField(default='19:00')),
                ('friday_closed', models.BooleanField(default=False)),
                ('saturday_open', models.TimeField(default='09:00')),
                ('saturday_close', models.TimeField(default='17:00')),
                ('saturday_closed', models.BooleanField(default=True)),
                ('sunday_open', models.TimeField(default='09:00')),
                ('sunday_close', models.TimeField(default='17:00')),
                ('sunday_closed', models.BooleanField(default=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='myapp.userprofile')),
            ],
            options={
                'db_table': 'business_hours',
                'unique_together': {('supplier',)},
            },
        ),
    ]
