# Generated by Django 5.1.6 on 2025-07-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
