# Generated by Django 5.1.6 on 2025-07-27 18:42

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='availability_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=27, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='availability_times',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('morning', 'Morning (09:00-12:00)'), ('afternoon', 'Afternoon (12:00-17:00)'), ('evening', 'Evening (17:00-21:00)')], max_length=25, null=True),
        ),
    ]
