# Generated by Django 5.1.6 on 2025-12-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_car_vin_alter_car_license_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='last_km_updated_at',
            field=models.DateField(verbose_name='Last Mileage Update'),
        ),
    ]
