# Generated by Django 5.1.6 on 2025-08-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_availability_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('mecanic_auto', 'Mecanic Auto'), ('autocolant_folie_auto', 'Autocolant & Folie Auto'), ('detailing_auto_profesionist', 'Detailing Auto Profesionist'), ('itp', 'ITP'), ('tapiterie_auto', 'Tapițerie Auto'), ('vulcanizare_auto_mobila', 'Vulcanizare Auto Mobilă'), ('tractari_auto', 'Tractări Auto'), ('tuning_auto', 'Tuning Auto')], max_length=50),
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
