# Generated by Django 5.1.6 on 2025-08-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_userprofile_is_active_userprofile_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierbrandservice',
            name='sector',
            field=models.CharField(blank=True, choices=[('sector_1', 'Sector 1'), ('sector_2', 'Sector 2'), ('sector_3', 'Sector 3'), ('sector_4', 'Sector 4'), ('sector_5', 'Sector 5'), ('sector_6', 'Sector 6'), ('no_sector', 'No Sector')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sector',
            field=models.CharField(blank=True, choices=[('sector_1', 'Sector 1'), ('sector_2', 'Sector 2'), ('sector_3', 'Sector 3'), ('sector_4', 'Sector 4'), ('sector_5', 'Sector 5'), ('sector_6', 'Sector 6'), ('no_sector', 'No Sector')], max_length=20, null=True),
        ),
    ]
