# Generated by Django 5.1.6 on 2025-08-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_supplierbrandservice_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='brand_photo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/'),
        ),
    ]
