# Generated by Django 5.1.6 on 2025-08-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_carbrand_brand_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_photo',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
