# Generated by Django 5.1.6 on 2025-08-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_service_service_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierbrandservice',
            name='city',
            field=models.CharField(choices=[('Bucharest', 'Bucharest'), ('Cluj-Napoca', 'Cluj-Napoca'), ('Timișoara', 'Timișoara'), ('Iași', 'Iași'), ('Constanța', 'Constanța'), ('Craiova', 'Craiova'), ('Brașov', 'Brașov'), ('Galați', 'Galați'), ('Ploiești', 'Ploiești'), ('Oradea', 'Oradea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='supplierbrandservice',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='supplierbrandservice',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
