# Generated by Django 5.1.6 on 2025-08-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_supplierbrandservice_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierbrandservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
