# Generated by Django 5.1.6 on 2025-08-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_supplierbrandservice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_photo',
            field=models.ImageField(upload_to='services/'),
        ),
    ]
