# Generated by Django 5.1.6 on 2025-08-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='is_all_cars',
            field=models.BooleanField(default=False, help_text='Check if this brand represents all car brands'),
        ),
    ]
