# Generated by Django 5.1.6 on 2025-08-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_carbrand_is_all_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbrand',
            name='is_all_cars',
        ),
    ]
