# Generated by Django 5.1.6 on 2025-08-10 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_carbrand_is_all_cars'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('is_open', models.BooleanField(default=True, help_text='Check if business is open on this day')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='myapp.userprofile')),
            ],
            options={
                'db_table': 'business_hours',
                'ordering': ['day_of_week'],
                'unique_together': {('supplier', 'day_of_week')},
            },
        ),
    ]
