# Generated by Django 5.1.6 on 2025-08-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_businesshours_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='businesshours',
            unique_together={('supplier',)},
        ),
    ]
