# Generated by Django 5.1.6 on 2025-08-10 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_businesshours_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='availability_days',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='availability_times',
        ),
    ]
