# Generated by Django 5.1.6 on 2025-08-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_userprofile_availability_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_photos',
            field=models.JSONField(blank=True, default=list, help_text='List of cover photo URLs'),
        ),
    ]
