# Generated by Django 5.1.6 on 2025-08-16 12:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_userprofile_cover_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverPhoto',
            fields=[
                ('photo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cover_photos',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cover_photos',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover_photos',
            field=models.ManyToManyField(blank=True, related_name='users', to='myapp.coverphoto'),
        ),
    ]
