# Generated by Django 5.1.6 on 2025-08-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_coverphoto_remove_userprofile_cover_photos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='address',
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], max_length=20),
        ),
    ]
