# Generated by Django 5.1.6 on 2025-08-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_request_address_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-5-25 12:00:00'),
            preserve_default=False,
        ),
    ]
