# Generated by Django 5.1.6 on 2025-08-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_request_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_message', 'New Message'), ('supplier_approval', 'Supplier Approval'), ('request_update', 'Request Update'), ('general_notification', 'General Notification')], max_length=50),
        ),
    ]
