# Generated by Django 5.1.6 on 2025-10-20 20:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRepresentative',
            fields=[
                ('representative_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(choices=[('Bucharest', 'Bucharest'), ('Cluj-Napoca', 'Cluj-Napoca'), ('Timișoara', 'Timișoara'), ('Iași', 'Iași'), ('Constanța', 'Constanța'), ('Craiova', 'Craiova'), ('Brașov', 'Brașov'), ('Galați', 'Galați'), ('Ploiești', 'Ploiești'), ('Oradea', 'Oradea')], max_length=50)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sales_representatives',
            },
        ),
        migrations.CreateModel(
            name='SupplierReferral',
            fields=[
                ('referral_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('has_received_commission', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='myapp.salesrepresentative')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='myapp.userprofile')),
            ],
            options={
                'db_table': 'supplier_referrals',
                'unique_together': {('sales_representative', 'supplier')},
            },
        ),
    ]
