# Generated by Django 5.1.6 on 2025-10-30 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_userprofile_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrepresentative',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone must be exactly 10 digits.')]),
        ),
    ]
