# Generated by Django 5.1.6 on 2025-11-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_alter_salesrepresentative_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('mecanic_auto', 'Mecanic Auto'), ('autocolant_folie_auto', 'Autocolant & Folie Auto'), ('detailing_auto_profesionist', 'Detailing Auto Profesionist'), ('itp', 'ITP'), ('tapiterie_auto', 'Tapițerie Auto'), ('vulcanizare_auto_mobila', 'Vulcanizare Auto Mobilă'), ('tractari_auto', 'Tractări Auto'), ('tuning_auto', 'Tuning Auto'), ('spalatorie_auto', 'Spălătorie Auto'), ('climatizare_auto', 'Climatizare Auto'), ('caroserie_si_vopsitorie', 'Caroserie și Vopsitorie')], max_length=50),
        ),
    ]
