# Generated by Django 5.1.6 on 2025-11-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrepresentative',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
