# Generated by Django 5.1.6 on 2025-11-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_salesrepresentative_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierbrandservice',
            name='photo_url',
        ),
    ]
